
MODULE ATOMIC_PROPERTIES
  USE physical_constants
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: L = 0.0
  DOUBLE PRECISION, PARAMETER :: S = 0.5
  DOUBLE PRECISION            :: J,F,gf,mf  
  DOUBLE PRECISION            :: gF_2,gF_1,G_F
  INTEGER                     :: Total_states_LSI
  DOUBLE PRECISION            :: mass_at,Ftotal,I,g_I,g_J,A,a_s,alpha_E,Fup,Fdown
  
  !87Rb
  DOUBLE PRECISION, PARAMETER :: mass_at_87Rb = 87*amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_87Rb  = 2.0
  DOUBLE PRECISION, PARAMETER :: I_87Rb       =  1.5  
  DOUBLE PRECISION, PARAMETER :: g_J_87Rb     =  2.0
  DOUBLE PRECISION, PARAMETER :: g_I_87Rb     = -0.000995
  DOUBLE PRECISION, PARAMETER :: A_87Rb       =  2*pi*hbar*3.417341E9
  DOUBLE PRECISION, PARAMETER :: a_s_87Rb     = 5.77E-9
  DOUBLE PRECISION, PARAMETER :: alpha_E_87Rb = 2*pi*hbar*0.0794*1E-4
  INTEGER,          PARAMETER :: Fup_87Rb     =  2
  INTEGER,          PARAMETER :: Fdown_87Rb   =  1

  !85Rb
  DOUBLE PRECISION, PARAMETER :: mass_at_85Rb = 85*amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_85Rb  = 2.0
  DOUBLE PRECISION, PARAMETER :: I_85Rb       =  1.5  
  DOUBLE PRECISION, PARAMETER :: g_J_85Rb     =  2.0
  DOUBLE PRECISION, PARAMETER :: g_I_85Rb     = -0.000995
  DOUBLE PRECISION, PARAMETER :: A_85Rb       =  2*pi*hbar*3.417341E9
  DOUBLE PRECISION, PARAMETER :: a_s_85Rb     = 5.77E-9
  DOUBLE PRECISION, PARAMETER :: alpha_E_85Rb = 2*pi*hbar*0.0794*1E-4
  INTEGER,          PARAMETER :: Fup_85Rb     =  2
  INTEGER,          PARAMETER :: Fdown_85Rb   =  1


  !6Li  
  DOUBLE PRECISION, PARAMETER :: mass_at_6Li = 6*amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_6Li  = 2.0
  DOUBLE PRECISION, PARAMETER :: I_6Li       =  1.5  
  DOUBLE PRECISION, PARAMETER :: g_J_6Li     =  2.0
  DOUBLE PRECISION, PARAMETER :: g_I_6Li     = -0.000995
  DOUBLE PRECISION, PARAMETER :: A_6Li       =  2*pi*hbar*3.417341E9
  DOUBLE PRECISION, PARAMETER :: a_s_6Li     = 5.77E-9
  DOUBLE PRECISION, PARAMETER :: alpha_E_6Li = 2*pi*hbar*0.0794*1E-4
  INTEGER,          PARAMETER :: Fup_6Li     =  2
  INTEGER,          PARAMETER :: Fdown_6Li   =  1


  !Cs
  DOUBLE PRECISION, PARAMETER :: mass_at_6Cs = 87*amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_6Cs  = 2.0
  DOUBLE PRECISION, PARAMETER :: I_6Cs       =  1.5  
  DOUBLE PRECISION, PARAMETER :: g_J_6Cs     =  2.0
  DOUBLE PRECISION, PARAMETER :: g_I_6Cs     = -0.000995
  DOUBLE PRECISION, PARAMETER :: A_6Cs       =  2*pi*hbar*3.417341E9
  DOUBLE PRECISION, PARAMETER :: a_s_6Cs     = 5.77E-9
  DOUBLE PRECISION, PARAMETER :: alpha_E_6Cs = 2*pi*hbar*0.0794*1E-4
  INTEGER,          PARAMETER :: Fup_6Cs     =  2
  INTEGER,          PARAMETER :: Fdown_6Cs   =  1


  !41K
  DOUBLE PRECISION, PARAMETER :: mass_at_6K = 41*amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_6K  = 2.0
  DOUBLE PRECISION, PARAMETER :: I_6K       =  1.5  
  DOUBLE PRECISION, PARAMETER :: g_J_6K     =  2.0
  DOUBLE PRECISION, PARAMETER :: g_I_6K     = -0.000995
  DOUBLE PRECISION, PARAMETER :: A_6K       =  2*pi*hbar*3.417341E9
  DOUBLE PRECISION, PARAMETER :: a_s_6K     = 5.77E-9
  DOUBLE PRECISION, PARAMETER :: alpha_E_6K = 2*pi*hbar*0.0794*1E-4
  INTEGER,          PARAMETER :: Fup_6K     =  2
  INTEGER,          PARAMETER :: Fdown_6K   =  1

  !Na
  DOUBLE PRECISION, PARAMETER :: mass_at_6Na = 87*amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_6Na  = 2.0
  DOUBLE PRECISION, PARAMETER :: I_6Na       =  1.5  
  DOUBLE PRECISION, PARAMETER :: g_J_6Na     =  2.0
  DOUBLE PRECISION, PARAMETER :: g_I_6Na     = -0.000995
  DOUBLE PRECISION, PARAMETER :: A_6Na       =  2*pi*hbar*3.417341E9
  DOUBLE PRECISION, PARAMETER :: a_s_6Na     = 5.77E-9
  DOUBLE PRECISION, PARAMETER :: alpha_E_6Na = 2*pi*hbar*0.0794*1E-4
  INTEGER,          PARAMETER :: Fup_6Na     =  2
  INTEGER,          PARAMETER :: Fdown_6Na   =  1


  !Qubit
  DOUBLE PRECISION, PARAMETER :: mass_at_qubit =  amu
  DOUBLE PRECISION, PARAMETER :: Ftotal_qubit  =  0.0
  DOUBLE PRECISION, PARAMETER :: I_qubit       =  0.0
  DOUBLE PRECISION, PARAMETER :: g_J_qubit     =  1.0
  DOUBLE PRECISION, PARAMETER :: g_I_qubit     =  0.0
  DOUBLE PRECISION, PARAMETER :: A_qubit       =  1.0
  DOUBLE PRECISION, PARAMETER :: a_s_qubit     =  0.0
  DOUBLE PRECISION, PARAMETER :: alpha_E_qubit =  0.0
  INTEGER,          PARAMETER :: Fup_qubit     =  0
  INTEGER,          PARAMETER :: Fdown_qubit   =  0.5

  
END MODULE ATOMIC_PROPERTIES


MODULE QUADRUPOLE_TOP_TRAP
  
  USE physical_constants
  
  DOUBLE PRECISION, PARAMETER :: alpha_TOP        =  170E-2
  DOUBLE PRECISION, PARAMETER :: B_TOP            =  3.22E-4
  DOUBLE PRECISION, PARAMETER :: OMEGA_TOP        = 2*pi*5.02E3
  DOUBLE PRECISION, PARAMETER :: OMEGA_RF_COOLING = 2*pi*4.0E6
  DOUBLE PRECISION            :: w_TOP_x,w_TOP_y,w_TOP_z,TEMPERATURE_TOP,x_0

END MODULE QUADRUPOLE_TOP_TRAP


MODULE MAGNETIC_BOTTLE
  
  USE physical_constants
  USE ATOMIC_PROPERTIES
  USE QUADRUPOLE_TOP_TRAP

!  DOUBLE PRECISION, PARAMETER :: A3 =
!  DOUBLE PRECISION, PARAMETER :: A1 =

END MODULE MAGNETIC_BOTTLE



MODULE ANTENNAS
  
  !DOUBLE PRECISION, PARAMETER :: M_mw =  0.1*2.5E-4/10.0!
  DOUBLE PRECISION             :: M_mw =  0.1*2.5E-4/10.0!
  DOUBLE PRECISION, PARAMETER :: M_rf =  24.0E-6!/2.0
  DOUBLE PRECISION, PARAMETER :: R_mw =  3.0E-3
  DOUBLE PRECISION, PARAMETER :: R_rf =  2.0E-3
  
END MODULE ANTENNAS



!!$MODULE ARRAYS
!!$
!!$  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Identity,CLEBSH_GORDAN_JtoF,j_x,j_y,j_z,I_x,I_y,I_z 
!!$  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_hyperfine,HAMILTONIAN,H_RF,H_FLOQUET,H_IJ,Z_M,H_OLD,U_ZEEMAN,Z_M_SUBSET
!!$  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_RF_DAGGER,H_ALPHA_DAGGER,H_ALPHA,H_FLOQUET_COPY,H_MW
!!$  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: observable, observable_extended, MW_coupling_dressedbasis
!!$  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: W_SPACE,W_SPACEF,W_SPACEF_0,E_OLD
!!$  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Fx,Fy,Fz,g_F_matrix
!!$  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: Hamiltonian_F,Identity_F,H_AUX,U_RF
!!$  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_FLOQUET_INTERACTION,H_FLOQUET_INTERACTION_DAGGER,H_FLOQUET_2D,H_FLOQUETBAND
!!$  INTEGER,          DIMENSION(:,:), ALLOCATABLE :: F_t,H_w,H_J,H_M,Jz_dash,Fz_dash
!!$  INTEGER,          DIMENSION(:),   ALLOCATABLE :: index_state
!!$  INTEGER                                       :: KD
!!$END MODULE ARRAYS
 

!!$MODULE subinterface
!!$  IMPLICIT NONE
!!$  INTERFACE
!!$     SUBROUTINE SETPARAMETERS(STEPPING,FIELD,INFO)       
!!$       USE TYPES
!!$       USE FLOQUET
!!$       IMPLICIT NONE
!!$       INTEGER,DIMENSION(:),INTENT(IN)    :: STEPPING
!!$       INTEGER,             INTENT(INOUT) :: INFO
!!$       TYPE(MODE),DIMENSION(MODES_NUM)    :: FIELD
!!$     END SUBROUTINE SETPARAMETERS
!!$
!!$     SUBROUTINE COUPLINGMATRICES_FBASIS(FIELD, H,INFO)
       
!!$ THE FIRST MODE IS STATIC AND PRODUCES ZEEMAN SHIFTS. 
!!$ COUPLINGS OF OTHER MODES ARE TRANSFORMED TO THE BASIS OF ZEEMAN STATES VIA U_ZEEMAN
       
!!$       
!!$       USE FLOQUET
!!$       USE ARRAYS
!!$       USE ATOMIC_PROPERTIES
!!$       USE TYPES
!!$       !USE SUBINTERFACE_LAPACK
!!$       
!!$       IMPLICIT NONE
!!$       TYPE(MODE), DIMENSION(MODES_NUM),INTENT(INOUT) :: FIELD
!!$       TYPE(MWCOUPLING),DIMENSION(9),INTENT(INOUT)    :: H
!!$       INTEGER,                         INTENT(INOUT) :: INFO
!!$     END SUBROUTINE COUPLINGMATRICES_FBASIS
!!$
!!$     SUBROUTINE STATES_CLASSIFICATION(H_FLOQUET,W_SPACE,SUBSPACES,N_FLOQUET,W_SUBSPACE,Total_states_LSI)
!!$       
!!$       IMPLICIT NONE
!!$       INTEGER,                        INTENT(IN) :: N_FLOQUET,SUBSPACES,Total_states_LSI
!!$       COMPLEX*16, DIMENSION(:,:),     INTENT(IN) :: H_FLOQUET
!!$       DOUBLE PRECISION, DIMENSION(:), INTENT(IN) :: W_SPACE
!!$       DOUBLE PRECISION, DIMENSION(:,:), INTENT(INOUT) :: W_SUBSPACE
!!$
!!$     END SUBROUTINE STATES_CLASSIFICATION  
!!$
!!$     SUBROUTINE I_and_J_representations(j_x,j_y,j_z,I_x,I_y,I_z,L,S,I)
!!$       
!!$       IMPLICIT  NONE
!!$       DOUBLE PRECISION, DIMENSION(:,:),INTENT(INOUT) :: j_x,j_y,j_z,I_x,I_y,I_z
!!$       DOUBLE PRECISION, INTENT(IN) :: L,S,I
!!$     END SUBROUTINE I_and_J_representations
!!$
!!$     SUBROUTINE F_representation(Fx,Fy,Fz,Ftotal)       
!!$       
!!$       IMPLICIT NONE
!!$       DOUBLE PRECISION, DIMENSION(:,:), INTENT(OUT):: Fx,Fy,Fz
!!$       DOUBLE PRECISION, INTENT(IN) :: Ftotal
!!$     END SUBROUTINE F_representation
          

!!$     SUBROUTINE WRITE_MATRIX(A)
!!$       DOUBLE PRECISION, DIMENSION(:,:) :: A
!!$     END SUBROUTINE  WRITE_MATRIX

!!$     SUBROUTINE WRITE_MATRIX_INT(A)
!!$       INTEGER, DIMENSION(:,:) :: A
!!$     END SUBROUTINE  WRITE_MATRIX_INT
!!$  END INTERFACE
!!$END MODULE subinterface
!!$
!!$
!!$MODULE SUBINTERFACE_LAPACK
!!$  IMPLICIT NONE
!!$  INTERFACE
!!$     SUBROUTINE LAPACK_FULLEIGENVALUES(H,N,W_SPACE,INFO)
!!$       IMPLICIT NONE
!!$       INTEGER,                        INTENT(IN)    :: N
!!$       COMPLEX*16, DIMENSION(:,:),     INTENT(INOUT) :: H  
!!$       DOUBLE PRECISION, DIMENSION(:), INTENT(OUT)   :: W_SPACE
!!$       INTEGER,                        INTENT(INOUT) :: INFO
!!$       
!!$     END SUBROUTINE LAPACK_FULLEIGENVALUES
!!$     
!!$     !SUBROUTINE LAPACK_SELECTEIGENVALUES(H,N,W_SPACE,Z_M,INFO)
!!$     SUBROUTINE LAPACK_SELECTEIGENVALUES(H,N,W_SPACE,L1,L2,Z_M,INFO)
!!$       
!!$       INTEGER,                        INTENT(IN)    :: N,L1,L2
!!$       COMPLEX*16, DIMENSION(:,:),     INTENT(INOUT) :: H
!!$       COMPLEX*16, DIMENSION(:,:),     INTENT(OUT)   :: Z_M
!!$       DOUBLE PRECISION, DIMENSION(:), INTENT(OUT)   :: W_SPACE
!!$       INTEGER,                        INTENT(OUT)   :: INFO
!!$     END SUBROUTINE LAPACK_SELECTEIGENVALUES
!!$
!!$     SUBROUTINE WRITE_MATRIX(A)
!!$       DOUBLE PRECISION, DIMENSION(:,:) :: A
!!$     END SUBROUTINE  WRITE_MATRIX
!!$
!!$     SUBROUTINE WRITE_MATRIX_INT(A)
!!$       INTEGER, DIMENSION(:,:) :: A
!!$     END SUBROUTINE  WRITE_MATRIX_INT
!!$
!!$
!!$  END INTERFACE
!!$END MODULE SUBINTERFACE_LAPACK
!!$
!!$
