PROGRAM MULTIMODEFLOQUET

  USE ATOMIC_PROPERTIES
  USE TYPES
  USE SUBINTERFACE
  USE SUBINTERFACE_LAPACK
  USE FLOQUETINIT_ 
  USE ARRAYS 

  IMPLICIT NONE
  TYPE(MODE),       DIMENSION(:),   ALLOCATABLE :: FIELDS
  TYPE(ATOM)                                       ID
  INTEGER,          DIMENSION(:),   ALLOCATABLE :: MODES_NUM
  INTEGER                                          TOTAL_FREQUENCIES,D_BARE
  INTEGER                                          INFO,m,INDEX0,r
  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: ENERGY,E_FLOQUET
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H__,U_F,U_AUX,U_B2D
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: P_AVG
  DOUBLE PRECISION                              :: T1,T2



  INFO = 0
  CALL FLOQUETINIT('qubit','U',2,ID,INFO)  

  D_BARE = ID%D_BARE
  ALLOCATE(P_AVG(D_BARE,D_BARE))
  ALLOCATE(U_AUX(D_BARE,D_BARE))
!  ALLOCATE(U_B2D(D_BARE,D_BARE))

  ALLOCATE(MODES_NUM(3))
  
  MODES_NUM(1) = 1 !(STATIC FIELD)
  MODES_NUM(2) = 2 !(DRIVING BY TWO HARMONICS)
  MODES_NUM(3) = 2 !(D\RVING BY A SECOND FREQUENCY)
!  MODES_NUM(4) = 2 !(DRVING BY A SECOND FREQUENCY)
  
  TOTAL_FREQUENCIES = SUM(MODES_NUM,1)
  ALLOCATE(FIELDS(TOTAL_FREQUENCIES))
  DO m=1,TOTAL_FREQUENCIES
     ALLOCATE(FIELDS(m)%V(ID%D_BARE,ID%D_BARE))
  END DO
  
  FIELDS(1)%X    = 0.0
  FIELDS(1)%Y    = 0.0
  FIELDS(1)%Z    = 2.0
  FIELDS(1)%phi_x = 0.0
  FIELDS(1)%phi_y = 0.0
  FIELDS(1)%phi_z = 0.0
  FIELDS(1)%omega = 0.0
  FIELDS(1)%N_Floquet = 0

  FIELDS(2)%X     = 4.0
  FIELDS(2)%Y     = 0.0
  FIELDS(2)%Z     = 0.0
  FIELDS(2)%phi_x = 0.0
  FIELDS(2)%phi_y = 0.0
  FIELDS(2)%phi_z = 0.0
  FIELDS(2)%omega = 2.0
  FIELDS(2)%N_Floquet = 3

!!$  FIELDS(3)%X     = 8.0
!!$  FIELDS(3)%y     = 0.0
!!$  FIELDS(3)%z     = 0.0
!!$  FIELDS(3)%phi_x = 0.0
!!$  FIELDS(3)%phi_y = 0.0
!!$  FIELDS(3)%phi_z = 0.0
!!$  FIELDS(3)%omega = 10
!!$  FIELDS(3)%N_Floquet = 1
!!$

  FIELDS(3)%X     = 8.0
  FIELDS(3)%y     = 0.0
  FIELDS(3)%z     = 0.0
  FIELDS(3)%phi_x = 0.0
  FIELDS(3)%phi_y = 0.0
  FIELDS(3)%phi_z = 0.0
  FIELDS(3)%omega = 2.0
  FIELDS(3)%N_Floquet = 1


  FIELDS(4)%X     = 8.0
  FIELDS(4)%y     = 0.0
  FIELDS(4)%z     = 0.0
  FIELDS(4)%phi_x = 0.0
  FIELDS(4)%phi_y = 0.0
  FIELDS(4)%phi_z = 0.0
  FIELDS(4)%omega = 10.0
  FIELDS(4)%N_Floquet = 3

  FIELDS(5)%X    = 12.0
  FIELDS(5)%Y    =  0.0
  FIELDS(5)%Z    =  0.0
  FIELDS(5)%phi_x = 0.0
  FIELDS(5)%phi_y = 0.0
  FIELDS(5)%phi_z = 0.0
  FIELDS(5)%omega = 20.0
  FIELDS(5)%N_Floquet = 1


  DO m=1,1!128

     ! --- SET DRIVING PARAMETERS 
!     FIELDS(2)%omega = 0.2 + (m-1)*1.0/128 
     CALL SETHAMILTONIANCOMPONENTS(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)

     !--- FIND THE MULTIMODE FLOQUET SPECTRUM 
     CALL MULTIMODEFLOQUETMATRIX(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)
     ALLOCATE(E_FLOQUET(SIZE(H_FLOQUET,1)))
     ALLOCATE(U_F(SIZE(H_FLOQUET,1),SIZE(H_FLOQUET,1)))
     E_FLOQUET = 0.0  
     CALL LAPACK_FULLEIGENVALUES(H_FLOQUET,SIZE(H_FLOQUET,1),E_FLOQUET,INFO)
     U_F = H_FLOQUET ! FOURIER DECOMPOSITION OF THE STATES DRESSED BY MODE NUMBER 
     DEALLOCATE(H_FLOQUET)
     write(*,*) e_floquet
     !--- EVALUATE THE AVERAGE TRANSITION PROBATILIBIES IN THE BARE BASIS
     P_AVG = 0.0
     CALL MULTIMODETRANSITIONAVG(SIZE(U_F,1),size(MODES_NUM,1),FIELDS,MODES_NUM,U_F,E_FLOQUET,ID%D_BARE,P_AVG,INFO) 
     
     !---  EVALUATE INSTANTANEOUS MULTIMODE FLOQUET TRANSFORMATION
     ALLOCATE(U_B2D(ID%D_BARE,SIZE(U_F,1)))
     T1 = 0.0
     write(*,*) size(modes_num,1)
     CALL MULTIMODEFLOQUETTRANSFORMATION(SIZE(U_F,1), SIZE(MODES_NUM,1),MODES_NUM,U_F,E_FLOQUET,ID%D_BARE,FIELDS,T1,U_B2D,INFO) 
     !P_AVG = ABS(U_B2D)**2   
     CALL WRITE_MATRIX(ABS(U_B2D)**2)
     
     !--- EVALUATE TIME-EVOLUTION OPERATOR IN THE BARE BASIS
     T1 = 0.0
     DO r=1,1!256
        T2 = r*32.0*4.0*atan(1.0)/256
        CALL MULTIMODETIMEEVOLUTINOPERATOR(SIZE(U_F,1),SIZE(MODES_NUM,1),MODES_NUM,U_F,E_FLOQUET,ID%D_BARE,FIELDS,T1,T2,U_AUX,INFO) 
        P_AVG = ABS(U_AUX)**2
        !CALL WRITE_MATRIX(ABS(U_AUX))
        CALL WRITE_MATRIX(P_AVG)
!        WRITE(*,*) t2,FIELDS(2)%OMEGA,ABS(U_AUX)**2
     END DO
     WRITE(*,*)
     DEALLOCATE(E_FLOQUET)
     DEALLOCATE(U_F)
  END DO
  
  
END PROGRAM MULTIMODEFLOQUET

