MODULE physical_constants
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: e            = 1.602176462E-19
  DOUBLE PRECISION, PARAMETER :: hbar         = 1.054E-34 
  DOUBLE PRECISION, PARAMETER :: mu_B         = 9.2740154E-24
  DOUBLE PRECISION, PARAMETER :: k_B          = 1.38E-23
  DOUBLE PRECISION, PARAMETER :: pi           = 3.1415926
  DOUBLE PRECISION, PARAMETER :: mu_cero      = 12.566370614E-7
  DOUBLE PRECISION, PARAMETER :: epsilon_cero = 8.854187817E-12 
  DOUBLE PRECISION, PARAMETER :: amu          = 1.660538921E-27
  DOUBLE PRECISION, PARAMETER :: g_t          = 9.8
  DOUBLE PRECISION, PARAMETER :: SB_ct        = 5.6704E-8
  COMPLEX*16,       PARAMETER :: J_IMAG       = DCMPLX(0.0,1.0)
  DOUBLE PRECISION, PARAMETER :: speedoflight = 299792458.0
  DOUBLE PRECISION            :: TOTAL_TIME
END MODULE physical_constants

MODULE ARRAYS

  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Identity,CLEBSH_GORDAN_JtoF,j_x,j_y,j_z,I_x,I_y,I_z 
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_hyperfine,HAMILTONIAN,H_RF,H_FLOQUET,H_IJ,Z_M,H_OLD,U_ZEEMAN,Z_M_SUBSET
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_RF_DAGGER,H_ALPHA_DAGGER,H_ALPHA,H_FLOQUET_COPY,H_MW
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: observable, observable_extended, MW_coupling_dressedbasis
  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: W_SPACE,W_SPACEF,W_SPACEF_0,E_OLD
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Fx,Fy,Fz,g_F_matrix
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: Hamiltonian_F,Identity_F,H_AUX,U_RF
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_FLOQUET_INTERACTION,H_FLOQUET_INTERACTION_DAGGER,H_FLOQUET_2D,H_FLOQUETBAND
  INTEGER,          DIMENSION(:,:), ALLOCATABLE :: F_t,H_w,H_J,H_M,Jz_dash,Fz_dash
  INTEGER,          DIMENSION(:),   ALLOCATABLE :: index_state
  INTEGER                                       :: KD
  DOUBLE PRECISION, DIMENSION(3)                :: POSITION,DELTA_POSITION

END MODULE ARRAYS
 
MODULE DCRFMWFIELDS
 IMPLICIT NONE
  ! DC, RF and MW parameters
  !! DC FIELD
  DOUBLE PRECISION B_DC_X, B_DC_Y, B_DC_Z   

  !! RF FIELD
  DOUBLE PRECISION  OMEGA_RF, PHI_RF_X,PHI_RF_Y,PHI_RF_Z
  DOUBLE PRECISION  B_RF_X,B_RF_Y,B_RF_Z

  !! MW FIELD
  DOUBLE PRECISION  OMEGA_MW, PHI_MW_X,PHI_MW_Y,PHI_MW_Z
  DOUBLE PRECISION  B_MW_X,B_MW_Y,B_MW_Z

END MODULE DCRFMWFIELDS

MODULE subinterface
  IMPLICIT NONE
  INTERFACE

!!$     SUBROUTINE COUPLINGMATRICES_FBASIS(FIELD, H,INFO)
!!$       
! THE FIRST MODE IS STATIC AND PRODUCES ZEEMAN SHIFTS. 
! COUPLINGS OF OTHER MODES ARE TRANSFORMED TO THE BASIS OF ZEEMAN STATES VIA U_ZEEMAN
!!$       
!!$       !USE FLOQUET
!!$       USE ARRAYS
!!$       USE TYPES
!!$       
!!$       IMPLICIT NONE
!!$       TYPE(MODE), DIMENSION(:),INTENT(INOUT) :: FIELD
!!$       TYPE(MWCOUPLING),DIMENSION(9),INTENT(INOUT)    :: H
!!$       INTEGER,                         INTENT(INOUT) :: INFO
!!$     END SUBROUTINE COUPLINGMATRICES_FBASIS
!!$
!!$     SUBROUTINE STATES_CLASSIFICATION(H_FLOQUET,W_SPACE,SUBSPACES,N_FLOQUET,W_SUBSPACE,Total_states_LSI)
!!$       
!!$       IMPLICIT NONE
!!$       INTEGER,                        INTENT(IN) :: N_FLOQUET,SUBSPACES,Total_states_LSI
!!$       COMPLEX*16, DIMENSION(:,:),     INTENT(IN) :: H_FLOQUET
!!$       DOUBLE PRECISION, DIMENSION(:), INTENT(IN) :: W_SPACE
!!$       DOUBLE PRECISION, DIMENSION(:,:), INTENT(INOUT) :: W_SUBSPACE
!!$
!!$     END SUBROUTINE STATES_CLASSIFICATION  

     SUBROUTINE I_and_J_representations(j_x,j_y,j_z,I_x,I_y,I_z,L,S,I)
       
       IMPLICIT  NONE
       DOUBLE PRECISION, DIMENSION(:,:),INTENT(INOUT) :: j_x,j_y,j_z,I_x,I_y,I_z
       DOUBLE PRECISION, INTENT(IN) :: L,S,I
     END SUBROUTINE I_and_J_representations

     SUBROUTINE F_representation(Fx,Fy,Fz,Ftotal_)       
       
       IMPLICIT NONE
       DOUBLE PRECISION, DIMENSION(:,:), INTENT(OUT):: Fx,Fy,Fz
       DOUBLE PRECISION, INTENT(IN) :: Ftotal_
     END SUBROUTINE F_representation
          
!!$     SUBROUTINE RFandMW_DRESSED_ENERGIES_STATES_RWA(D,q,FIELD,ENERGY_MODES,U,INFO)
!!$
!!$       !    PROCEDURE TO OBTAIN RF DRESSED ENERGIES IN A ROTATING FRAME
!!$       ! D,IN   : MATRIX DIMENSION
!!$       ! q, in, : integer, step parameters
!!$       ! FIELD,IN: FIELD CONFIGURAITON
!!$       ! ENERGY_MODES, OUT  : DRESSED ENERGY
!!$       ! U: OUT TRANSFORMATION BETWEEN BARE AND DRESSED BASIS
!!$       !INFO: ERROR FLAG
!!$       
!!$       !USE FLOQUET
!!$       USE TYPES
!!$
!!$       IMPLICIT NONE
!!$       INTEGER,                              INTENT(IN)    :: d,q
!!$       DOUBLE PRECISION, DIMENSION(D,9),     INTENT(OUT)   :: ENERGY_MODES
!!$       INTEGER,                              INTENT(INOUT) :: INFO
!!$       TYPE(MODE), DIMENSION(:),     INTENT(IN)    :: FIELD
!!$       TYPE(HARMONIC_FACTORS), DIMENSION(9), INTENT(OUT)   :: U
!!$
!!$     END SUBROUTINE RFandMW_DRESSED_ENERGIES_STATES_RWA

     SUBROUTINE SET_ATOMIC_PARAMETERS(ATOMICSPECIE,MANIFOLD,JTOTAL,ID,INFO)
       ! ATOMICSPECIE: 87Rb,6Li,Cs,41K,qubit,lattice, SPIN
       ! MANIFOLD : "U" UPPER HYPERFINE MANIFOLD, "L" LOWER HYPERFIND MANIFOLD, "B" BOTH
       ! JTOTAL   :  IF ATOMICSPECIE .EQ. SPIN THEN JTOTAL IS THE TOTAL ANGULAR MOMENTUM OF THE SPIN
       !             IF ATOMICSPECIE .EQ. LATTICE, THEN JTOTAL IS THE NUMBER OF SITES
       USE TYPES
       IMPLICIT NONE
       CHARACTER (LEN=4),OPTIONAL, INTENT(IN) :: ATOMICSPECIE
       CHARACTER (LEN=1),OPTIONAL, INTENT(IN) :: MANIFOLD  !
       INTEGER,          OPTIONAL, INTENT(IN) :: JTOTAL
       TYPE(ATOM),INTENT(OUT) :: ID
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SET_ATOMIC_PARAMETERS

  END INTERFACE
END MODULE subinterface


MODULE SUBINTERFACE_LAPACK

  IMPLICIT NONE
  PUBLIC 
  INTERFACE
     SUBROUTINE LAPACK_FULLEIGENVALUES(H,N,W_SPACE,INFO)
       IMPLICIT NONE
       INTEGER,                        INTENT(IN)    :: N
       COMPLEX*16, DIMENSION(:,:),     INTENT(INOUT) :: H  
       DOUBLE PRECISION, DIMENSION(:), INTENT(OUT)   :: W_SPACE
       INTEGER,                        INTENT(INOUT) :: INFO
       
     END SUBROUTINE LAPACK_FULLEIGENVALUES
     
     SUBROUTINE LAPACK_SELECTEIGENVALUES(H,N,W_SPACE,L1,L2,Z_M,INFO)
       
       INTEGER,                        INTENT(IN)    :: N,L1,L2
       COMPLEX*16, DIMENSION(:,:),     INTENT(INOUT) :: H
       COMPLEX*16, DIMENSION(:,:),     INTENT(OUT)   :: Z_M
       DOUBLE PRECISION, DIMENSION(:), INTENT(OUT)   :: W_SPACE
       INTEGER,                        INTENT(OUT)   :: INFO
     END SUBROUTINE LAPACK_SELECTEIGENVALUES

     SUBROUTINE WRITE_MATRIX(A)
       DOUBLE PRECISION, DIMENSION(:,:) :: A
     END SUBROUTINE  WRITE_MATRIX

     SUBROUTINE WRITE_MATRIX_INT(A)
       INTEGER, DIMENSION(:,:) :: A
     END SUBROUTINE  WRITE_MATRIX_INT
     
  END INTERFACE
END MODULE SUBINTERFACE_LAPACK

MODULE FLOQUETINIT_
  INTERFACE
     SUBROUTINE FLOQUETINIT(atomicspecie,manifold,JTOTAL,ID,info)
       ! ATOMICSPECIE: 87Rb,6Li,Cs,41K,qubit,lattice, SPIN
       ! MANIFOLD : "U" UPPER HYPERFINE MANIFOLD, "L" LOWER HYPERFIND MANIFOLD, "B" BOTH
       ! JTOTAL   :  IF ATOMICSPECIE .EQ. SPIN THEN JTOTAL IS THE TOTAL ANGULAR MOMENTUM OF THE SPIN
       !             IF ATOMICSPECIE .EQ. LATTICE, THEN JTOTAL IS THE NUMBER OF SITES
       

       ! calculate the dimenson of the Hilbert space
       ! initialize all the matrices required for a full Floquet calcuations
       ! Calculate the nuclear, electron and total angular momentum operators
       
       USE TYPES
       USE SUBINTERFACE_LAPACK

       IMPLICIT NONE
       
       CHARACTER (LEN=*),OPTIONAL, INTENT(IN)    :: ATOMICSPECIE
       CHARACTER (LEN=*),OPTIONAL, INTENT(IN)    :: MANIFOLD  !
       INTEGER,          OPTIONAL, INTENT(IN)    :: JTOTAL
       TYPE(ATOM),       OPTIONAL, INTENT(OUT)   :: ID
       INTEGER,                    INTENT(INOUT) :: INFO
       
     END SUBROUTINE FLOQUETINIT
  END INTERFACE
END MODULE FLOQUETINIT_

