SUBROUTINE MULTIMODEFLOQUETTRANSFORMATION(D,NM,MODES_NUM,U_F_MODES,E_MULTIFLOQUET,D_BARE,FIELD,T1,U,INFO) 

  ! TIME-DEPENDENT TRANSFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES
  ! U(T1) = sum_ U^n exp(i n omega T1)
  ! 
!!$  D              (IN)   : DIMENSION OF THE EXTENDED HILBERT SPACE (SIZE OF THE MULTIMODE FLOQUET MATRIX)
!!$  NM             (IN)   : NUMBER OF MODES            
!!$  MODES_NUM      (IN)   : VECTOR (NM) INDICATING THE NUMBER OF HARMONICS OF EACH MODE
!!$  U_F_MODES      (IN)   : TRANSFORMATION, DIMENSOON (D,D) 
!!$  E_MULTIFLOQUET (IN)   : MULTIMODE FLOQUET SPECTRUM
!!$  D_BARE         (IN)   : DIMENSION OF THE BARE HILBERT SPACE
!!$  FIELD          (IN)   : STRUCTURE DESCRIBING THE COUPLINGS
!!$  T1             (IN)   : TIME. THE BARE 2 DRESSED TRANSFORMATINO IS TIME DEPENDENT
!!$  U              (OUT)  : TRANFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES, DIMENSION (D_BARE,D)
!!$  INFO           (INOUT): (POSSIBLE) ERROR FLAG
 
  USE TYPES

  IMPLICIT NONE
  INTEGER,                                    INTENT(IN)    :: D,D_BARE,NM ! DIMENSION OF THE MULTIMODE FLOQUET SPACE AND THE BARE BASIS
  INTEGER,                                    INTENT(INOUT) :: INFO
  INTEGER,          DIMENSION(NM),            INTENT(IN)    :: MODES_NUM
  TYPE(MODE),       DIMENSION(NM),            INTENT(IN)    :: FIELD  ! FIELDS PROPERTIES: FREQUENCY, AMPLITUDES AND PHASES
  DOUBLE PRECISION,                           INTENT(IN)    :: T1 ! IN SECONDS
  DOUBLE PRECISION, DIMENSION(D),             INTENT(IN)    :: E_MULTIFLOQUET ! SET OF MULTIMODE FLOQUET ENERGIES, IN Hz, TO AVOID HBAR FACTORS
  COMPLEX*16,       DIMENSION(D,D),           INTENT(IN)    :: U_F_MODES ! TRANFORMATION MATRIX BETWEEN DRESSED FLOQUET AND BARE EXTENDED BASIS
  COMPLEX*16,       DIMENSION(D_BARE,D),      INTENT(OUT)   :: U ! TIME-DEPENDENT TRANSFORMATINO BETWEEN THE DRESSED AND EXTENDED BARE BASIS


  COMPLEX*16,       DIMENSION(D,D)      :: U_DIAGONAL
  COMPLEX*16,       DIMENSION(D_BARE,D) :: U_AUX

  INTEGER                                                :: MULTIMODE_HARMONICS, n,i,j,m,index0,index1,FIELD_INDEX
  INTEGER,                DIMENSION(NM)                  :: N_FLOQUET
  DOUBLE PRECISION,       DIMENSION(NM)                  :: OMEGA_VEC
  TYPE(HARMONIC_FACTORS), DIMENSION(:),      ALLOCATABLE :: U_MODES_n
  DOUBLE PRECISION                                       :: PHASE

  MULTIMODE_HARMONICS   = D/D_BARE
  ALLOCATE(U_MODES_n(MULTIMODE_HARMONICS))
  DO n=1,MULTIMODE_HARMONICS
     ALLOCATE(U_MODES_n(n)%U(D_BARE,D))
     U_MODES_n(n)%U = 0.0
     ALLOCATE(U_MODES_n(n)%n(NM))
     U_MODES_n(n)%n = 0
  END DO

  N_FLOQUET = 0
  OMEGA_VEC = 0

  DO n=2,NM
     FIELD_INDEX  = 2+SUM(MODES_NUM(2:n-1))
     N_FLOQUET(n) = FIELD(FIELD_INDEX)%N_Floquet
     OMEGA_VEC(n) = FIELD(FIELD_INDEX)%OMEGA 
     !     write(*,*) n,N_FLOQUET(n),field_index,modes_num(n)
     IF(modes_num(n).GT.N_FLOQUET(n)+1) THEN
        WRITE(*,*) "TO BUILD THE EXTENDED HAMILTONIAN THE NUMBER OF FLOQUET MODES MUST BE DEFINED"
        WRITE(*,*) "LARGER THAN THE NUMBER OF FIELD MODES"
        INFO = -10
     END IF
  END DO
 ! DO i=1,NM
 !    OMEGA_VEC(i) = FIELD(i)%OMEGA
 ! END DO


  i  = 1
  DO index1=1,MULTIMODE_HARMONICS
     DO n=1,D
        j = n
        i = 1 + (index1-1)*D_BARE 
        DO m=1,D_BARE
           U_MODES_n(index1)%U(m,n) = U_F_MODES(i,j)
           i = i + 1           
        END DO
     END DO
  END DO

  DO i=0,MULTIMODE_HARMONICS-1
     U_MODES_n(i+1)%n = 0
     index0 = i
     DO j=2,NM
        U_MODES_n(i+1)%n(j)= -N_FLOQUET(j) + MOD(index0,(2*N_FLOQUET(j)+1))
        index0 = INT(index0/(2*N_FLOQUET(j)+1))
     END DO
  END DO


  U = 0.0
  DO index1=1,MULTIMODE_HARMONICS
     PHASE = DOT_PRODUCT(U_MODES_n(index1)%n,omega_vec)*T1
     U      = U  + EXP(DCMPLX(0.0,1.0)*PHASE)*U_MODES_n(index1)%U
  END DO


END SUBROUTINE MULTIMODEFLOQUETTRANSFORMATION


!SUBROUTINE MULTIMODEFLOQUETMICROMOTION(D,NM,MODES_NUM,U_F_MODES,E_MULTIFLOQUET,D_BARE,FIELD,T1,U,INFO) 
!
!  ! TIME-DEPENDENT TRANSFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES
!  ! U(T1) = sum_ U^n exp(i n omega T1)
!  ! 
!!!$  D              (IN)   : DIMENSION OF THE EXTENDED HILBERT SPACE (SIZE OF THE MULTIMODE FLOQUET MATRIX)
!!!$  NM             (IN)   : NUMBER OF MODES            
!!!$  MODES_NUM      (IN)   : VECTOR (NM) INDICATING THE NUMBER OF HARMONICS OF EACH MODE
!!!$  U_F_MODES      (IN)   : TRANSFORMATION, DIMENSOON (D,D) 
!!!$  E_MULTIFLOQUET (IN)   : MULTIMODE FLOQUET SPECTRUM
!!!$  D_BARE         (IN)   : DIMENSION OF THE BARE HILBERT SPACE
!!!$  FIELD          (IN)   : STRUCTURE DESCRIBING THE COUPLINGS
!!!$  T1             (IN)   : TIME. THE BARE 2 DRESSED TRANSFORMATINO IS TIME DEPENDENT
!!!$  U              (OUT)  : TRANFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES, DIMENSION (D_BARE,D)
!!!$  INFO           (INOUT): (POSSIBLE) ERROR FLAG
! 
!  USE TYPES
!
!  IMPLICIT NONE
!  INTEGER,                                    INTENT(IN)    :: D,D_BARE,NM ! DIMENSION OF THE MULTIMODE FLOQUET SPACE AND THE BARE BASIS
!  INTEGER,                                    INTENT(INOUT) :: INFO
!  INTEGER,          DIMENSION(NM),            INTENT(IN)    :: MODES_NUM
!  TYPE(MODE),       DIMENSION(NM),            INTENT(IN)    :: FIELD  ! FIELDS PROPERTIES: FREQUENCY, AMPLITUDES AND PHASES
!  DOUBLE PRECISION,                           INTENT(IN)    :: T1 ! IN SECONDS
!  DOUBLE PRECISION, DIMENSION(D),             INTENT(IN)    :: E_MULTIFLOQUET ! SET OF MULTIMODE FLOQUET ENERGIES, IN Hz, TO AVOID HBAR FACTORS
!  COMPLEX*16,       DIMENSION(D,D),           INTENT(IN)    :: U_F_MODES ! TRANFORMATION MATRIX BETWEEN DRESSED FLOQUET AND BARE EXTENDED BASIS
!  COMPLEX*16,       DIMENSION(D_BARE,D_BARE), INTENT(OUT)   :: U ! TIME-DEPENDENT TRANSFORMATINO BETWEEN THE DRESSED AND BARE BASIS WITH ZERO HARMONICS
!
!
!  COMPLEX*16,       DIMENSION(D,D)      :: U_DIAGONAL
!  COMPLEX*16,       DIMENSION(D_BARE,D) :: U_AUX
!
!  INTEGER                                                :: MULTIMODE_HARMONICS, n,i,j,m,index0,index1,FIELD_INDEX,INDEX_L
!  INTEGER,                DIMENSION(NM)                  :: N_FLOQUET
!  DOUBLE PRECISION,       DIMENSION(NM)                  :: OMEGA_VEC
!  TYPE(HARMONIC_FACTORS), DIMENSION(:),      ALLOCATABLE :: U_MODES_n
!  DOUBLE PRECISION                                       :: PHASE
!
!  MULTIMODE_HARMONICS   = D/D_BARE
!  ALLOCATE(U_MODES_n(MULTIMODE_HARMONICS))
!  DO n=1,MULTIMODE_HARMONICS
!     ALLOCATE(U_MODES_n(n)%U(D_BARE,D))
!     U_MODES_n(n)%U = 0.0
!     ALLOCATE(U_MODES_n(n)%n(NM))
!     U_MODES_n(n)%n = 0
!  END DO
!
!  N_FLOQUET = 0
!  OMEGA_VEC = 0
!
!  DO n=2,NM
!     FIELD_INDEX  = 2+SUM(MODES_NUM(2:n-1))
!     N_FLOQUET(n) = FIELD(FIELD_INDEX)%N_Floquet
!     OMEGA_VEC(n) = FIELD(FIELD_INDEX)%OMEGA 
!     !     write(*,*) n,N_FLOQUET(n),field_index,modes_num(n)
!     IF(modes_num(n).GT.N_FLOQUET(n)+1) THEN
!        WRITE(*,*) "TO BUILD THE EXTENDED HAMILTONIAN THE NUMBER OF FLOQUET MODES MUST BE DEFINED"
!        WRITE(*,*) "LARGER THAN THE NUMBER OF FIELD MODES"
!        INFO = -10
!     END IF
!  END DO
! ! DO i=1,NM
! !    OMEGA_VEC(i) = FIELD(i)%OMEGA
! ! END DO
!
!
!  i  = 1
!  DO index1=1,MULTIMODE_HARMONICS
!     DO n=1,D
!        j = n
!        i = 1 + (index1-1)*D_BARE 
!        DO m=1,D_BARE
!           U_MODES_n(index1)%U(m,n) = U_F_MODES(i,j)
!           i = i + 1           
!        END DO
!     END DO
!  END DO
!
!  DO i=0,MULTIMODE_HARMONICS-1
!     U_MODES_n(i+1)%n = 0
!     index0 = i
!     DO j=2,NM
!        U_MODES_n(i+1)%n(j)= -N_FLOQUET(j) + MOD(index0,(2*N_FLOQUET(j)+1))
!        index0 = INT(index0/(2*N_FLOQUET(j)+1))
!     END DO
!  END DO
!
!
!  U_AUX = 0.0
!  DO index1=1,MULTIMODE_HARMONICS
!     PHASE = DOT_PRODUCT(U_MODES_n(index1)%n,omega_vec)*T1
!     U_AUX      = U_AUX  + EXP(DCMPLX(0.0,1.0)*PHASE)*U_MODES_n(index1)%U
!  END DO
!
!  !INDEX_L = d_bare*d_bare*(((dressingfloquetdimension/d_bare) - 1)/2);
!  INDEX_L = D_BARE* ((D/D_BARE - 1)/2)!D/2 - D_BARE/2   
!  U = U_AUX(1:D_BARE,INDEX_L+1:INDEX_L+D_BARE)
!
!END SUBROUTINE MULTIMODEFLOQUETMICROMOTION



SUBROUTINE MULTIMODEMICROMOTION(D,NM,MODES_NUM,U_F_MODES,E_MULTIFLOQUET,D_BARE,FIELD,T1,U,INFO) 

  ! TIME-DEPENDENT TRANSFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES
  ! U(T1) = sum_ U^n exp(i n omega T1)
  ! 
!!$  D              (IN)   : DIMENSION OF THE EXTENDED HILBERT SPACE (SIZE OF THE MULTIMODE FLOQUET MATRIX)
!!$  NM             (IN)   : NUMBER OF MODES            
!!$  MODES_NUM      (IN)   : VECTOR (NM) INDICATING THE NUMBER OF HARMONICS OF EACH MODE
!!$  U_F_MODES      (IN)   : TRANSFORMATION, DIMENSOON (D,D) 
!!$  E_MULTIFLOQUET (IN)   : MULTIMODE FLOQUET SPECTRUM
!!$  D_BARE         (IN)   : DIMENSION OF THE BARE HILBERT SPACE
!!$  FIELD          (IN)   : STRUCTURE DESCRIBING THE COUPLINGS
!!$  T1             (IN)   : TIME. THE BARE 2 DRESSED TRANSFORMATINO IS TIME DEPENDENT
!!$  U              (OUT)  : TRANFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES, DIMENSION (D_BARE,D)
!!$  INFO           (INOUT): (POSSIBLE) ERROR FLAG
 
  !USE TYPES_C
  USE TYPES
  !USE MODES_4F
  USE SUBINTERFACE_LAPACK

  IMPLICIT NONE
  INTEGER,                                    INTENT(IN)    :: D,D_BARE,NM ! DIMENSION OF THE MULTIMODE FLOQUET SPACE AND THE BARE BASIS
  INTEGER,                                    INTENT(INOUT) :: INFO
  INTEGER,          DIMENSION(NM),            INTENT(IN)    :: MODES_NUM
  TYPE(MODE),       DIMENSION(NM),            INTENT(IN)    :: FIELD  ! FIELDS PROPERTIES: FREQUENCY, AMPLITUDES AND PHASES
  DOUBLE PRECISION,                           INTENT(IN)    :: T1 ! IN SECONDS
  DOUBLE PRECISION, DIMENSION(D),             INTENT(IN)    :: E_MULTIFLOQUET ! SET OF MULTIMODE FLOQUET ENERGIES, IN Hz, TO AVOID HBAR FACTORS
  COMPLEX*16,       DIMENSION(D,D),           INTENT(IN)    :: U_F_MODES ! TRANFORMATION MATRIX BETWEEN DRESSED FLOQUET AND BARE EXTENDED BASIS
  COMPLEX*16,       DIMENSION(D_BARE,D_BARE), INTENT(OUT)   :: U ! TIME-DEPENDENT TRANSFORMATINO BETWEEN THE DRESSED AND EXTENDED BARE BASIS

    
  COMPLEX*16,       DIMENSION(D_BARE,D) :: U_AUX ! TIME-DEPENDENT TRANSFORMATINO BETWEEN THE DRESSED AND EXTENDED BARE BASIS

  INTEGER INDEX0
  
  !WRITE(*,*) "MICROMOTION SUBROUTINE    "
  CALL MULTIMODEFLOQUETTRANSFORMATION(D,NM,MODES_NUM,U_F_MODES,E_MULTIFLOQUET,D_BARE,FIELD,T1,U_AUX,INFO) 
  INDEX0 = D_BARE*FIELD(2)%N_FLOQUET
  !WRITE(*,*) INDEX0
  !CALL WRITE_MATRIX(ABS(U_AUX(1:D_BARE,INDEX0+1:INDEX0+D_BARE)))
  U = U_AUX(1:D_BARE,INDEX0+1:INDEX0+D_BARE)
  INDEX0 = D_BARE* ((D/D_BARE - 1)/2)!D/2 - D_BARE/2   
  !WRITE(*,*) INDEX0
  !CALL WRITE_MATRIX(ABS(U_AUX(1:D_BARE,INDEX0+1:INDEX0+D_BARE)))
  
  
END SUBROUTINE MULTIMODEMICROMOTION


